.TH "" "" "" "" ""
.SH json2html\-biblio
.RS
.PP
No name given yet
.RE
.SS Install
.PP
Install it with
.IP
.nf
\f[C]
npm\ install\ json2html\-biblio
\f[]
.fi
.SS Usage
.IP
.nf
\f[C]
Usage:
\ \ \ \ json2html\-biblio\ (\ \-h\ |\ \-\-help\ )

Options:
\ \ \ \ \-h,\ \-\-help\ \ \ \ \ \ \ \ \ \ \ \ \ \ help\ for\ json2html\-biblio

Commands:

Arguments:
\f[]
.fi
.SS Author
.IP \[bu] 2
Vittorio Zaccaria
.SS License
.PP
Released under the BSD License.
.PP
   *   *   *   *   *
